/**
 * 前端示例兜底数据（仅用于未配置 Coze 时预览界面）
 * 在网址后加 ?mock=1 即可使用，例如：index.html?mock=1
 * 结构与 Coze 工作流输出一致；id / rank / color 由前端渲染时补充。
 */
window.MOCK_REPORT = {
  trackInfo: {
    name: '自媒体AI工具赛道',
    desc: '聚焦小红书等平台低粉爆款笔记，拆解选题方向与内容打法，帮你快速定位可复用的爆款逻辑。',
    updateDate: '2026-07-09'
  },
  topicTypes: [
    { name: '自媒体运营', percent: 40 },
    { name: 'AI工具', percent: 30 },
    { name: '涨粉技巧', percent: 15 },
    { name: '内容创作', percent: 10 },
    { name: '剪辑技巧', percent: 5 }
  ],
  newViral: [
    { format: 'video', title: '我用AI把废片剪成爆款，全过程公开', author: '阿May的剪辑台', heat: '2.4w', topic: '剪辑技巧',
      breakdown: ['选题切口是「AI拯救废片」，精准击中新手「拍了很多但剪不出」的痛点。', '结构采用「前后对比+分步演示」，前3秒直接放成片钩子，完播率显著高于同类。'],
      hotComments: [{ user: '剪辑小白', text: '原来转场还能这么丝滑，马上去试', like: '1203' }, { user: '运营喵', text: '求同款AI工具名字！', like: '876' }],
      topicRecommend: ['AI拯救废片实录', '手机也能做的3个高级转场', '剪映隐藏功能盘点'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n1' },
    { format: 'image', title: '0基础做自媒体第30天，收入第一次破千', author: '小白涨粉日记', heat: '3.1w', topic: '自媒体运营',
      breakdown: ['用「日更打卡+真实数据」建立人设信任，读者有陪伴感和参照感。', '封面统一模板+数字标题，提升信息密度与点击率。'],
      hotComments: [{ user: '想做博主', text: '请问第一个月是怎么熬过来的', like: '2104' }, { user: '柠檬', text: '收入构成能细说吗', like: '988' }],
      topicRecommend: ['自媒体30天复盘模板', '新手第一个月做什么', '副业收入拆解'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n2' },
    { format: 'video', title: '这个AI脚本工具，让我日更不再焦虑', author: '内容创作所', heat: '1.8w', topic: 'AI工具',
      breakdown: ['卖点不是工具多强，而是「把日更门槛打下来」，情绪价值拉满。', '演示用真实账号后台，展示从灵感→脚本→发布全链路。'],
      hotComments: [{ user: '日更困难户', text: '求工具名，已关注', like: '765' }, { user: '阿杰', text: '免费版够用吗', like: '430' }],
      topicRecommend: ['AI脚本工具横评', '日更不焦虑的3个方法', '一个人怎么做内容团队'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n3' },
    { format: 'image', title: '小红书起号最狠的5个选题，直接抄', author: '运营老王', heat: '4.2w', topic: '涨粉技巧',
      breakdown: ['标题用「直接抄」降低行动成本，清单体天然高收藏。', '内容给出可执行的选题模板，而非空泛方法论，收藏率极高。'],
      hotComments: [{ user: '收藏家', text: '已抄，下周就发', like: '3320' }, { user: 'momo', text: '第3个我试过真的有用', like: '1502' }],
      topicRecommend: ['起号选题清单模板', '高收藏笔记的共性', '新手避坑选题'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n4' },
    { format: 'video', title: '一条视频涨粉2万，我做对了什么', author: '涨粉实战营', heat: '2.9w', topic: '涨粉技巧',
      breakdown: ['以「复盘爆款」视角输出，既能蹭自己流量又能做教学人设。', '重点讲「选题判断+发布时机」，弱化运气强调方法，可信度高。'],
      hotComments: [{ user: '想涨粉', text: '发布时间具体几点啊', like: '1890' }, { user: '小林', text: '求更详细的复盘', like: '770' }],
      topicRecommend: ['爆款复盘方法论', '最佳发布时间测试', '涨粉内容的共性'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n5' },
    { format: 'image', title: '剪辑新手必看：3个被低估的转场', author: '剪映小课堂', heat: '1.5w', topic: '剪辑技巧',
      breakdown: ['「被低估」制造稀缺感，比「常用转场」更有点击欲。', '图文分步截图+参数标注，新手可照抄，实用性强。'],
      hotComments: [{ user: '剪辑萌新', text: '第二个绝了', like: '640' }, { user: '阿橙', text: '能出视频版吗', like: '310' }],
      topicRecommend: ['剪映参数对照表', '新手剪辑流程', '转场使用时机'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n6' },
    { format: 'video', title: 'AI配音翻车现场，但流量反而爆了', author: '搞笑阿强', heat: '2.0w', topic: 'AI工具',
      breakdown: ['反向选题：「翻车」比「成功」更有传播力，评论区互动意愿强。', '用真实翻车片段引发共鸣，结尾给补救方案，情绪闭环完整。'],
      hotComments: [{ user: '哈哈怪', text: '笑死，我也是这样', like: '1120' }, { user: '小鹿', text: '补救那招学到了', like: '560' }],
      topicRecommend: ['AI工具翻车合集', '配音翻车怎么救', '搞笑向涨粉逻辑'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n7' },
    { format: 'image', title: '自媒体工具箱大公开，省下万元学费', author: '省钱小能手', heat: '3.6w', topic: '自媒体运营',
      breakdown: ['「省万元」强利益点，清单体高收藏高转发。', '工具按使用场景分组，降低选择成本，实用价值高。'],
      hotComments: [{ user: '剁手党', text: '第5个神器已下载', like: '2010' }, { user: 'momo', text: '有没有免费的', like: '980' }],
      topicRecommend: ['免费工具清单', '自媒体必备App', '降本增效工具'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n8' },
    { format: 'video', title: '从0到1万粉，我的复盘全记录', author: '复盘君', heat: '2.2w', topic: '涨粉技巧',
      breakdown: ['长线「成长记录」人设，粉丝有代入感，容易追更。', '用数据图表讲阶段打法，弱化鸡血强调节奏。'],
      hotComments: [{ user: '追更人', text: '坐等2万粉复盘', like: '1330' }, { user: '阿哲', text: '第一阶段最难吧', like: '620' }],
      topicRecommend: ['阶段成长复盘', '0到1万粉节奏', '追更型人设怎么做'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n9' },
    { format: 'image', title: '爆款标题的万能公式，建议收藏', author: '标题党克星', heat: '5.0w', topic: '内容创作',
      breakdown: ['「万能公式+建议收藏」双重收藏钩子，数据极高。', '给出可套用模板而非抽象原则，读者能立刻上手。'],
      hotComments: [{ user: '收藏狂魔', text: '公式3直接套用了', like: '4200' }, { user: '小美', text: '求更多公式', like: '1880' }],
      topicRecommend: ['标题模板库', '高点击封面公式', '开头3秒钩子'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-n10' }
  ],
  lowFanViral: [
    { format: 'video', title: '新号第3条就爆了，只因做对1件事', author: '小鹿同学', fans: '860', heat: '1.2w', topic: '涨粉技巧',
      breakdown: ['爆点在于「单点归因」：把成功归结为一个可复制动作，降低模仿门槛。', '新号身份反而增强可信度——「和我一样的新手也能行」。'],
      hotComments: [{ user: '同新手', text: '请问那1件事是啥', like: '980' }, { user: 'momo', text: '我第5条了还没爆', like: '540' }],
      topicRecommend: ['新号起量单点打法', '新手第一条怎么发', '低粉也能爆的选题'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l1' },
    { format: 'image', title: '素人也能做的爆款选题清单', author: '平平无奇', fans: '420', heat: '9800', topic: '内容创作',
      breakdown: ['「素人」身份即卖点，精准吸引同为新手的庞大群体。', '清单体+零门槛描述，收藏率远高于教程类。'],
      hotComments: [{ user: '普通用户', text: '第2个我已经发了', like: '760' }, { user: '阿白', text: '求更多素人选题', like: '430' }],
      topicRecommend: ['素人友好选题', '零基础内容方向', '不露脸也能做'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l2' },
    { format: 'video', title: '我替你们试了10个AI工具，这个最香', author: '工具控阿橙', fans: '730', heat: '1.5w', topic: 'AI工具',
      breakdown: ['「替你试错」的人设极省读者时间，信任感强。', '实测对比+明确结论，比单纯罗列工具更有决策价值。'],
      hotComments: [{ user: '选择困难', text: '结论太清楚了', like: '1100' }, { user: '小宇', text: '第7个求名字', like: '520' }],
      topicRecommend: ['AI工具实测横评', '新手该用哪个AI', '免费AI工具推荐'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l3' },
    { format: 'image', title: '0粉起步，第一条笔记就破万赞', author: '萌新大魔王', fans: '150', heat: '1.1w', topic: '自媒体运营',
      breakdown: ['「0粉破万赞」强反差标题，制造强烈好奇与点击。', '内容复盘了封面与标题的具体做法，可复用性强。'],
      hotComments: [{ user: '羡慕党', text: '第一条就这么猛', like: '1340' }, { user: 'momo', text: '封面用的什么', like: '610' }],
      topicRecommend: ['新号首条打法', '高赞封面怎么做', '0粉起步指南'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l4' },
    { format: 'video', title: '下班后2小时做自媒体，真实记录', author: '打工人小李', fans: '640', heat: '8600', topic: '自媒体运营',
      breakdown: ['「打工人」身份引发强烈共鸣，场景真实有陪伴感。', '记录而非教学，靠真实感涨粉，适合低粉起步。'],
      hotComments: [{ user: '同打工人', text: '这就是我', like: '720' }, { user: '阿强', text: '时间怎么挤出来的', like: '350' }],
      topicRecommend: ['副业时间管理', '打工人做号记录', '下班后2小时'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l5' },
    { format: 'image', title: '不会写文案？套这个模板就行', author: '文案搬运工', fans: '910', heat: '1.3w', topic: '内容创作',
      breakdown: ['「套模板」直击痛点，把写作门槛降到填空级别。', '模板结构化呈现，读者可照抄，收藏价值高。'],
      hotComments: [{ user: '文案发愁', text: '填空就行太香了', like: '990' }, { user: '小敏', text: '求更多模板', like: '480' }],
      topicRecommend: ['万能文案模板', '开头结尾句式', '文案填空库'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l6' },
    { format: 'video', title: '一条评论区神回复，带火整条视频', author: '神回复选手', fans: '280', heat: '7200', topic: '涨粉技巧',
      breakdown: ['选题独特：讲「评论区运营」而非内容本身，信息差明显。', '用真实神回复案例示范，可操作、易模仿。'],
      hotComments: [{ user: '评论区常客', text: '学到了互动技巧', like: '560' }, { user: 'momo', text: '求更多案例', like: '290' }],
      topicRecommend: ['评论区运营技巧', '神回复怎么写', '提升互动率'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l7' },
    { format: 'image', title: '新手必收藏：剪辑避坑指南', author: '踩坑专业户', fans: '550', heat: '6500', topic: '剪辑技巧',
      breakdown: ['「避坑」比「教程」更抓人，负面情绪共鸣强。', '以自身踩坑经历带出正确做法，可信度高。'],
      hotComments: [{ user: '踩过坑', text: '第3个我中过', like: '510' }, { user: '阿橙', text: '求视频版', like: '240' }],
      topicRecommend: ['剪辑常见坑', '新手避坑清单', '导出参数设置'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l8' },
    { format: 'video', title: '用AI生成封面，点击率翻倍实测', author: '封面研究所', fans: '880', heat: '1.0w', topic: 'AI工具',
      breakdown: ['「实测」二字建立可信度，用前后数据对比说话。', '聚焦单一变量（封面），结论清晰可复制。'],
      hotComments: [{ user: '封面苦手', text: '马上去试AI封面', like: '880' }, { user: '小鹿', text: '用的哪个工具', like: '420' }],
      topicRecommend: ['AI封面生成实测', '高点击封面要素', '封面AB测试'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l9' },
    { format: 'image', title: '起号第7天，我摸到了流量密码', author: '摸鱼小张', fans: '360', heat: '9200', topic: '涨粉技巧',
      breakdown: ['「第7天」具体时间锚点，制造阶段感与期待。', '分享摸索过程而非结果，真实感强，适合低粉借鉴。'],
      hotComments: [{ user: '同第7天', text: '我还在迷茫', like: '670' }, { user: 'momo', text: '密码是啥', like: '330' }],
      topicRecommend: ['起号第一周打法', '流量密码拆解', '新手节奏规划'],
      sourceUrl: 'https://www.xiaohongshu.com/explore/example-l10' }
  ]
};
